<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jack</string>
	</array>
	<key>name</key>
	<string>Jack</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(class|int|char|boolean|void)\b</string>
			<key>name</key>
			<string>storage.type.jack</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(constructor|function|method)\b</string>
			<key>name</key>
			<string>storage.modifier.jack</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(field|static|var)\b</string>
			<key>name</key>
			<string>storage.modifier.jack</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(let|if|else|while|do|return)\b</string>
			<key>name</key>
			<string>keyword.control.jack</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.jack</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.jack</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.jack</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.jack</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|null|this)\b</string>
			<key>name</key>
			<string>constant.language.jack</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.jack</string>
	<key>uuid</key>
	<string>2e3a09a4-fda2-4161-b54e-537b76a6fe71</string>
</dict>
</plist>
